## Colors configuration
[colors.primary]
background = "#10081d"
foreground = "#9fd3e3"

[colors.normal]
black   = "#10081d"
red     = "#6E1C8E"
green   = "#602793"
yellow  = "#4F59A2"
blue    = "#9728AC"
magenta = "#AC43C8"
cyan    = "#DD66E7"
white   = "#9fd3e3"

[colors.bright]
black   = "#6f939e"
red     = "#6E1C8E"
green   = "#602793"
yellow  = "#4F59A2"
blue    = "#9728AC"
magenta = "#AC43C8"
cyan    = "#DD66E7"
white   = "#9fd3e3"
