## Colors configuration
[colors.primary]
background = "#121318"#13001f"
foreground = "#e490d0"

[colors.normal]
black   = "#13001f"
red     = "#FE5A60"
green   = "#560989"
yellow  = "#6A0E92"
blue    = "#7815BF"
magenta = "#7422A6"
cyan    = "#9121AA"
white   = "#e490d0"

[colors.bright]
black   = "#9f6491"
red     = "#FE5A60"
green   = "#560989"
yellow  = "#6A0E92"
blue    = "#7815BF"
magenta = "#7422A6"
cyan    = "#9121AA"
white   = "#e490d0"
