## Colors configuration
[colors.primary]
background = "#05090F"
foreground = "#f4edc0"

[colors.normal]
black   = "#05090F"
red     = "#207B7E"
green   = "#435545"
yellow  = "#AE411F"
blue    = "#E0BB4A"
magenta = "#16E4F0"
cyan    = "#40C9CE"
white   = "#f4edc0"

[colors.bright]
black   = "#aaa586"
red     = "#207B7E"
green   = "#435545"
yellow  = "#AE411F"
blue    = "#E0BB4A"
magenta = "#16E4F0"
cyan    = "#40C9CE"
white   = "#f4edc0"
