## Colors configuration
background #05090F
foreground #f4edc0
selection_background #f4edc0
selection_foreground #05090F
cursor #f4edc0

color0 #05090F
color8 #aaa586
color1 #207B7E
color9 #207B7E
color2 #435545
color10 #435545
color3 #AE411F
color11 #AE411F
color4 #E0BB4A
color12 #E0BB4A
color5 #16E4F0
color13 #16E4F0
color6 #40C9CE
color14 #40C9CE
color7 #f4edc0
color15 #f4edc0
