# Shell variables
# Generated by 'wal'
wallpaper='/home/dave/Pictures/wallpapers/ethereal.jpg'

# Special
background='#040916'
foreground='#a7bfe0'
cursor='#a7bfe0'

# Colors
color0='#040916'
color1='#4C316E'
color2='#3B437A'
color3='#304F97'
color4='#3D4A97'
color5='#5A549A'
color6='#9A5EA5'
color7='#a7bfe0'
color8='#74859c'
color9='#4C316E'
color10='#3B437A'
color11='#304F97'
color12='#3D4A97'
color13='#5A549A'
color14='#9A5EA5'
color15='#a7bfe0'

