# Shell variables
# Generated by 'wal'
wallpaper='/home/dave/Pictures/wallpapers/girl_hacker.jpg'

# Special
background='#05090F'
foreground='#f4edc0'
cursor='#f4edc0'

# Colors
color0='#05090F'
color1='#207B7E'
color2='#435545'
color3='#AE411F'
color4='#E0BB4A'
color5='#16E4F0'
color6='#40C9CE'
color7='#f4edc0'
color8='#aaa586'
color9='#207B7E'
color10='#435545'
color11='#AE411F'
color12='#E0BB4A'
color13='#16E4F0'
color14='#40C9CE'
color15='#f4edc0'

