# Shell variables
# Generated by 'wal'
wallpaper='/home/dave/Pictures/wallpapers/1-synthwave-84.jpg'

# Special
background='#121318'#13001f'
foreground='#e490d0'
cursor='#e490d0'

# Colors
color0='#13001f'
color1='#FE5A60'
color2='#560989'
color3='#6A0E92'
color4='#7815BF'
color5='#7422A6'
color6='#9121AA'
color7='#e490d0'
color8='#9f6491'
color9='#FE5A60'
color10='#560989'
color11='#6A0E92'
color12='#7815BF'
color13='#7422A6'
color14='#9121AA'
color15='#e490d0'

