#!/usr/bin/env bash

# Import Current Theme
DIR="$HOME/.config/niri"
RASI="$DIR/rofi/asroot.rasi"
ASROOT="$DIR/scripts/asroot"
USER=`whoami`

# Theme Elements
prompt='Root'
mesg='Run Applications As Root'
term="alacritty --class alacritty-float,alacritty-float --config-file /home/$USER/.config/niri/alacritty/alacritty.toml"

# Options
layout=`cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$layout" == 'NO' ]]; then
	option_1=' Alacritty'
	option_2=' Thunar'
	option_3=' Geany'
	option_4=' Ranger'
	option_5=' Vim'
else
	option_1=''
	option_2=''
	option_3=''
	option_4=''
	option_5=''
fi

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5" | rofi_cmd
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		${ASROOT} "$term"
	elif [[ "$1" == '--opt2' ]]; then
		${ASROOT} 'dbus-run-session thunar'
	elif [[ "$1" == '--opt3' ]]; then
		${ASROOT} geany
	elif [[ "$1" == '--opt4' ]]; then
		${ASROOT} "$term -e ranger"
	elif [[ "$1" == '--opt5' ]]; then
		${ASROOT} "$term -e vim"
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		run_cmd --opt1
        ;;
    $option_2)
		run_cmd --opt2
        ;;
    $option_3)
		run_cmd --opt3
        ;;
    $option_4)
		run_cmd --opt4
        ;;
    $option_5)
		run_cmd --opt5
        ;;
esac
