## Colors configuration
[colors-dark]
alpha=1.0
foreground=8fd6d5
background=0A0918

## Normal/regular colors (color palette 0-7)
regular0=0A0918  # black
regular1=284D46  # red
regular2=B9434D  # green
regular3=26B173  # yellow
regular4=F0B758  # blue
regular5=155E9E  # magenta
regular6=1A76CC  # cyan
regular7=8fd6d5  # white

## Bright colors (color palette 8-15)
bright0=649595   # bright black
bright1=284D46   # bright red
bright2=B9434D   # bright green
bright3=26B173   # bright yellow
bright4=F0B758   # bright blue
bright5=155E9E   # bright magenta
bright6=1A76CC   # bright cyan
bright7=8fd6d5   # bright white
