## Colors configuration
[colors-dark]
alpha=1.0
foreground=e490d0
background=13001f

## Normal/regular colors (color palette 0-7)
regular0=13001f  # black
regular1=FE5A60  # red
regular2=560989  # green
regular3=6A0E92  # yellow
regular4=7815BF  # blue
regular5=7422A6  # magenta
regular6=9121AA  # cyan
regular7=e490d0  # white

## Bright colors (color palette 8-15)
bright0=9f6491   # bright black
bright1=FE5A60   # bright red
bright2=560989   # bright green
bright3=6A0E92   # bright yellow
bright4=7815BF   # bright blue
bright5=7422A6   # bright magenta
bright6=9121AA   # bright cyan
bright7=e490d0   # bright white
