## Colors configuration
[colors-dark]
alpha=1.0
foreground=9fd3e3
background=10081d

## Normal/regular colors (color palette 0-7)
regular0=10081d  # black
regular1=6E1C8E  # red
regular2=602793  # green
regular3=4F59A2  # yellow
regular4=9728AC  # blue
regular5=AC43C8  # magenta
regular6=DD66E7  # cyan
regular7=9fd3e3  # white

## Bright colors (color palette 8-15)
bright0=6f939e   # bright black
bright1=6E1C8E   # bright red
bright2=602793   # bright green
bright3=4F59A2   # bright yellow
bright4=9728AC   # bright blue
bright5=AC43C8   # bright magenta
bright6=DD66E7   # bright cyan
bright7=9fd3e3   # bright white
