## Colors configuration
[colors-dark]
alpha=1.0
foreground=f4edc0
background=05090F

## Normal/regular colors (color palette 0-7)
regular0=05090F  # black
regular1=207B7E  # red
regular2=435545  # green
regular3=AE411F  # yellow
regular4=E0BB4A  # blue
regular5=16E4F0  # magenta
regular6=40C9CE  # cyan
regular7=f4edc0  # white

## Bright colors (color palette 8-15)
bright0=aaa586   # bright black
bright1=207B7E   # bright red
bright2=435545   # bright green
bright3=AE411F   # bright yellow
bright4=E0BB4A   # bright blue
bright5=16E4F0   # bright magenta
bright6=40C9CE   # bright cyan
bright7=f4edc0   # bright white
