#!/usr/bin/env bash

## Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/niri"
RASI="$DIR/rofi/launcher.rasi"

# Run
rofi \
    -show drun \
	-theme ${RASI}
